import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "@/public/globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const montserrat = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning suppressContentEditableWarning className={`${montserrat.className} antialiased flex flex-col items-center justify-start gap-y-3 px-120 py-6`}>
        <Header />

        {/* Global Background Decorations */}
        <div className='fixed inset-0 w-full h-full overflow-hidden -z-50 pointer-events-none'>
          <div className='absolute -top-[10%] -right-[10%] w-[50vw] h-[50vw] max-w-[600px] max-h-[600px] bg-blue-500/20 rounded-full blur-[80px] mix-blend-screen opacity-70'></div>
          <div className='absolute -bottom-[10%] -left-[10%] w-[50vw] h-[50vw] max-w-[600px] max-h-[600px] bg-purple-500/10 rounded-full blur-[80px] mix-blend-screen opacity-70'></div>
        </div>

        {children}
        <Footer />
      </body>
    </html>
  );
}
